### ISSUE TITLE
Fields for user table.

### ISSUE THREAD

**Issue by Sparassidae** [TravisSpark/spark-database#1]
- id **INTEGER NOT NULL PRIMARY KEY**
- name **VARCHAR(25) NOT NULL**
  - last
  - first
- contact information
  - email **VARCHAR(30) NULL UNIQUE**
  - phone **INTEGER NULL**
- Unit **VARCHAR(20) NULL**
- Section **VARCHAR(30) NULL**
- Date entered into database **automatically filled when entered into database**
- RFID # **VARCHAR(?) NULL UNIQUE**

**Comment by TangoYankee** [comment]
[Validate Email](https://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html)
